console.log('Hello World');
console.log(123);
console.log(true);
var greeting = 'Hello';
console.log(greeting);
console.log([1,2,3,4]);
console.log({a:1,b:2});
console.table({a:1,b:2});
console.error('This is an error');
console.clear();
console.warn('This is a warning');
console.time('Tables');
console.log(123);
console.log(123);
console.log(123);
console.log(123);
console.timeEnd('Tables');